<?php

return [
    // Scienza, Medicina, Ricerca
    'fas fa-dna' => 'DNA (Genetica)',
    'fas fa-flask' => 'Ampolla (Chimica)',
    'fas fa-microscope' => 'Microscopio',
    'fas fa-atom' => 'Atomo',
    'fas fa-brain' => 'Cervello',
    'fas fa-biohazard' => 'Rischio Biologico',
    'fas fa-capsules' => 'Capsule',
    'fas fa-radiation' => 'Radiazioni',
    'fas fa-heartbeat' => 'Battito Cardiaco',
    'fas fa-lungs' => 'Polmoni',
    'fas fa-pills' => 'Pillole',
    'fas fa-syringe' => 'Siringa',
    'fas fa-thermometer' => 'Termometro',
    'fas fa-eye' => 'Occhio',
    'fas fa-infinity' => 'Infinito',
    'fas fa-compass' => 'Bussola',
    
    // Natura e Animali
    'fas fa-tree' => 'Albero',
    'fas fa-leaf' => 'Foglia',
    'fas fa-seedling' => 'Germoglio',
    'fas fa-paw' => 'Zampa',
    'fas fa-fish' => 'Pesce',
    'fas fa-frog' => 'Rana',
    'fas fa-spider' => 'Ragno',
    'fas fa-crow' => 'Corvo',
    'fas fa-feather' => 'Piuma',
    'fas fa-bone' => 'Osso',
    'fas fa-cat' => 'Gatto',
    'fas fa-dog' => 'Cane',
    'fas fa-dove' => 'Colomba',
    'fas fa-dragon' => 'Drago',
    'fas fa-hippo' => 'Ippopotamo',
    'fas fa-otter' => 'Lontra',
    'fas fa-horse' => 'Cavallo',
    'fas fa-carrot' => 'Carota',
    'fas fa-apple-alt' => 'Mela',
    
    // Elementi e Forze
    'fas fa-fire' => 'Fuoco',
    'fas fa-tint' => 'Acqua (Goccia)',
    'fas fa-bolt' => 'Fulmine',
    'fas fa-wind' => 'Vento',
    'fas fa-snowflake' => 'Neve/Ghiaccio',
    'fas fa-cloud' => 'Nuvola',
    'fas fa-cloud-sun' => 'Soleggiato',
    'fas fa-cloud-showers-heavy' => 'Pioggia Forte',
    'fas fa-sun' => 'Sole',
    'fas fa-moon' => 'Luna',
    'fas fa-meteor' => 'Meteora',
    'fas fa-volcano' => 'Vulcano',
    'fas fa-water' => 'Acqua (Corrente)',
    'fas fa-mountain' => 'Montagna',
    
    // Combattimento, Protezione, Pericolo
    'fas fa-shield-alt' => 'Scudo',
    'fas fa-fist-raised' => 'Pugno',
    'fas fa-skull' => 'Teschio',
    'fas fa-skull-crossbones' => 'Teschio e Ossa',
    'fas fa-bomb' => 'Bomba',
    'fas fa-crosshairs' => 'Mirino',
    'fas fa-exclamation-triangle' => 'Pericolo',
    'fas fa-fire-extinguisher' => 'Estintore',
    'fas fa-gas-mask' => 'Maschera Antigas',
    'fas fa-hand-rock' => 'Pugno Chiuso',
    'fas fa-heart' => 'Cuore',
    
    // Strumenti, Oggetti, Logica
    'fas fa-cogs' => 'Ingranaggi (Logica)',
    'fas fa-cog' => 'Ingranaggio',
    'fas fa-tools' => 'Strumenti',
    'fas fa-wrench' => 'Chiave Inglese',
    'fas fa-hammer' => 'Martello',
    'fas fa-code' => 'Codice',
    'fas fa-anchor' => 'Ancora',
    'fas fa-key' => 'Chiave',
    'fas fa-lock' => 'Lucchetto',
    'fas fa-unlock' => 'Lucchetto Aperto',
    'fas fa-map' => 'Mappa',
    'fas fa-trophy' => 'Trofeo',
    'fas fa-briefcase' => 'Valigetta',
    'fas fa-book' => 'Libro',
    'fas fa-gamepad' => 'Gamepad',
    'fas fa-gem' => 'Gemma/Risorsa',
    'fas fa-calculator' => 'Calcolatrice',
    'fas fa-crown' => 'Corona',
    'fas fa-gift' => 'Regalo',
    'fas fa-bell' => 'Campana',
    'fas fa-camera' => 'Fotocamera',
    'fas fa-clock' => 'Orologio',
    'fas fa-hourglass' => 'Clessidra',
    'fas fa-calendar' => 'Calendario',
    'fas fa-binoculars' => 'Binocolo',
    'fas fa-battery-full' => 'Batteria Carica',
    'fas fa-lightbulb' => 'Lampadina',
    'fas fa-magnet' => 'Magnete',
    'fas fa-paperclip' => 'Graffetta',
    'fas fa-trash' => 'Cestino',
    'fas fa-umbrella' => 'Ombrello',
    'fas fa-shopping-cart' => 'Carrello',
    
    // Edifici, Luoghi
    'fas fa-home' => 'Casa',
    'fas fa-building' => 'Edificio',
    'fas fa-store' => 'Negozio',
    'fas fa-warehouse' => 'Magazzino',
    'fas fa-church' => 'Chiesa',
    'fas fa-city' => 'Città',
    'fas fa-hospital' => 'Ospedale',
    'fas fa-hotel' => 'Hotel',
    'fas fa-university' => 'Università',
    
    // Persone e Simboli Sociali
    'fas fa-user' => 'Umano/Utente',
    'fas fa-users' => 'Persone/Gruppo',
    'fas fa-user-ninja' => 'Ninja',
    'fas fa-user-astronaut' => 'Astronauta',
    'fas fa-user-secret' => 'Agente Segreto',
    'fas fa-user-shield' => 'Guardia',
    'fas fa-user-tie' => 'Professionista',
    'fas fa-user-friends' => 'Amici',
    'fas fa-male' => 'Uomo',
    'fas fa-female' => 'Donna',
    'fas fa-baby' => 'Neonato',
    
    // Veicoli e Viaggi
    'fas fa-car' => 'Automobile',
    'fas fa-truck' => 'Autocarro',
    'fas fa-plane' => 'Aereo',
    'fas fa-ship' => 'Nave',
    'fas fa-rocket' => 'Razzo',
    'fas fa-bicycle' => 'Bicicletta',
    'fas fa-motorcycle' => 'Moto',
    'fas fa-subway' => 'Metropolitana',
    'fas fa-helicopter' => 'Elicottero',
    'fas fa-space-shuttle' => 'Navetta Spaziale',
    
    // UI, Frecce e Indicatori
    'fas fa-check' => 'Spunta (Ok)',
    'fas fa-times' => 'Croce (Errore)',
    'fas fa-plus' => 'Più',
    'fas fa-minus' => 'Meno',
    'fas fa-search' => 'Cerca',
    'fas fa-info-circle' => 'Informazione',
    'fas fa-question-circle' => 'Aiuto/Domanda',
    'fas fa-arrow-up' => 'Freccia Su',
    'fas fa-arrow-down' => 'Freccia Giù',
    'fas fa-arrow-left' => 'Freccia Sinistra',
    'fas fa-arrow-right' => 'Freccia Destra',
    'fas fa-chevron-up' => 'Chevron Su',
    'fas fa-chevron-down' => 'Chevron Giù',
    'fas fa-chevron-left' => 'Chevron Sinistra',
    'fas fa-chevron-right' => 'Chevron Destra',
    'fas fa-sync' => 'Sincronizza',
    'fas fa-undo' => 'Annulla',
    'fas fa-redo' => 'Ripristina',
    'fas fa-play' => 'Avvia',
    'fas fa-pause' => 'Pausa',
    'fas fa-stop' => 'Ferma',
    
    // Audio, Media, Comunicazione
    'fas fa-volume-up' => 'Volume Alto',
    'fas fa-volume-mute' => 'Muto',
    'fas fa-microphone' => 'Microfono',
    'fas fa-headphones' => 'Cuffie',
    'fas fa-tv' => 'Televisione',
    'fas fa-mobile-alt' => 'Smartphone',
    'fas fa-envelope' => 'Busta/Email',
    'fas fa-comments' => 'Discussioni',
    'fas fa-comment' => 'Commento',
    
    // Grafici, Dati, File
    'fas fa-chart-bar' => 'Istogramma',
    'fas fa-chart-pie' => 'Grafico a Torta',
    'fas fa-chart-line' => 'Grafico a Linee',
    'fas fa-folder' => 'Cartella',
    'fas fa-folder-open' => 'Cartella Aperta',
    'fas fa-file' => 'File generico',
    'fas fa-file-alt' => 'Documento di Testo',
    'fas fa-file-code' => 'Codice Sorgente',
    'fas fa-file-image' => 'Immagine',
    'fas fa-file-pdf' => 'Documento PDF',
    'fas fa-database' => 'Database',
    'fas fa-server' => 'Server',
    'fas fa-hdd' => 'Disco Rigido',
    'fas fa-wifi' => 'Connessione Wifi',
    'fas fa-ethernet' => 'Cavo di Rete',
    'fas fa-plug' => 'Presa di Corrente',
];
